name: hetimafile
version: 0.0.1
description: A starting point for Dart libraries or applications.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  hetimacore:
    git: https://github.com/kyorohiro/dart_hetimacore.git
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
